### ISSUE TITLE
Key is truncated too early

### ISSUE THREAD

**Issue by cbegin** [vbatts/go-google-authenticator#2]
See this line:

https://github.com/vbatts/go-google-authenticator/blob/master/auth/auth.go#L111

It truncates the state too early and results in an incorrect hash.
```
	err := binary.Write(&buf_in, binary.BigEndian, int32(t_chunk))
```

Change it to write a 64 bit integer, and voila... all good. 
```
	err := binary.Write(&buf_in, binary.BigEndian, int64(t_chunk))
```

Cheers.

**Comment by vbatts** [comment]
thanks @cbegin !
